service: jerrypic-canvas-service

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  convertForKual:
    handler: index.convertForKual
    events:
      - s3:
          bucket: jerrypic
          event: s3:ObjectCreated:*
          rules:
            - prefix: kual-assets/
            - suffix: .png
          existing: true
      - s3:
          bucket: jerrypic
          event: s3:ObjectCreated:*
          rules:
            - prefix: kual-assets/
            - suffix: .jpg
          existing: true