AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'canvas - functions to convert images for target frame'
Resources:
  Canvas:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.convertForKual
      Runtime: nodejs10.x
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 120
      Role: 'arn:aws:iam::212092276746:role/canvas-role'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .png
  Bucket1:
    Type: 'AWS::S3::Bucket'